title: "Dankers Lab"
subtitle: "Home lab dashboard"
logo: "https://raw.githubusercontent.com/bastienwirtz/homer/main/public/logo.png"

links: []

services:
  - name: "Documents"
    icon: "fas fa-file-alt"
    items:
      - name: "Receipts (Paperless)"
        subtitle: "Document Management"
        tag: "Office"
        url: "https://archive.dankers.io"
  - name: "Media"
    items:
      - name: "jellyfin"
      - name: "rsfeed"

