http:
  middlewares:
    paperless-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
          Remote-User: ""
        customResponseHeaders:
          X-Content-Type-Options: "nosniff"
