# Middlewares for header forwarding and security


http:
  middlewares:
    paperless-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Content-Type-Options: "nosniff"
