http:
  routers:
    homer:
      rule: "Host(`home.dankers.io`)"
      service: homer
      entryPoints:
        - web

    paperless:
      rule: "Host(`archive.dankers.io`)"
      service: paperless
      entryPoints:
        - web
      middlewares:
        - paperless-headers
